# Generated by Django 3.0.3 on 2020-03-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_thread_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='categories',
            field=models.CharField(choices=[('GEN', 'General'), ('ENT', 'Entertaiment'), ('SCI', 'Science'), ('TEC', 'Technology')], default='GEN', max_length=3),
        ),
    ]
